version: '3'

services:
 ner:
  image: "insuradar/smartgenie_ner:latest"
  restart: always
  volumes:
   - ./Server:/apps/ner
   - ./model:/model
  entrypoint: /apps/ner/docker-entry.sh 

 ocr:
  image: "insuradar/smartgenie_ocr:latest"
  restart: always
  volumes:
   - ./INSUR:/apps/ocr
   - ./model:/model
  ports:
   - 8090:8080
  entrypoint: /apps/ocr/docker-entry.sh
